### ISSUE TITLE
Use wait_for_status to avoid index initialize issues

### ISSUE THREAD

**Issue by orangejulius** [missinglink/elastictest#2]
Right now there's a 500ms timer to wait for a newly created test index to be initialized. That's not a bad choice, but especially in slower environments like TravisCI tests, it might not always be enough, leading to intermittent failures.

Can we throw a sync call to Elasticsearch's wait_for_status API to completely remove that possibility?

It would also mean tests finish faster if the index does happen to finish faster, for those of us counting miliseconds :watch: :eyes:

**Comment by missinglink** [comment]
Hmmm. my understanding is that the wait_for_status API is to wait on `cluster health` (ie. shards have come up after startup).

The issue with the tests is that we have PUT the data and then REFRESH but the mappings etc. have not been updated.

I think what we really need is the 'block until refresh' feature that has been in the works since forever:
https://github.com/elastic/elasticsearch/issues/1063

**Comment by missinglink** [comment]
Also I think the issue is worse when using `dynamic_templates` because when you `PUT` the first doc it has to copy the mapping from there and then create a new index, although that is pure speculation.

**Comment by missinglink** [comment]
I'll implement this anyway, it won't hurt.
